version: '3.9'

services:
  ecommerce_app:
    container_name: ecommerce_backend
    image: shop_app:latest
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    #env_file:
     # - .env
