version: '3.9'

services:
  ecommerce_app:
    container_name: ecommerce_backend
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=5000
      - DJANGO_SETTINGS_MODULE=config.settings
    command: ./entrypoint.sh
