version: '3.9'

services:
  ecommerce_app:
    container_name: ecommerce_app
    image: shop_app:latest
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env