version: '3.9'

services:
  db:
    image: postgis/postgis:14-3.3
    container_name: ecommerce_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ecommerce_app:
    build: .
    container_name: ecommerce_backend
    env_file: .env
    depends_on:
      - db
    ports:
      - "9000:9000"
    command: ./entrypoint.sh

volumes:
  postgres_data:
