version: '3.9'

services:
  ecommerce_app:
    container_name: ecommerce_backend
    image: shop_app:latest
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=config.settings
    command: python manage.py runserver 0.0.0.0:5000
