# Generated by Django 5.2 on 2025-05-07 15:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Marque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ArchivedBoutique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_id", models.IntegerField()),
                ("nom", models.CharField(max_length=100)),
                ("adresse", models.TextField()),
                ("ville", models.CharField(max_length=50)),
                ("code_postal", models.CharField(max_length=5)),
                ("departement", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9),
                ),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9),
                ),
                ("date_archivage", models.DateTimeField(auto_now_add=True)),
                ("raison", models.TextField()),
                (
                    "archive_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_boutiques",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArchivedProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_id", models.IntegerField()),
                ("nom", models.CharField(max_length=100)),
                ("marque", models.CharField(max_length=50)),
                ("modele", models.CharField(max_length=50)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("couleur", models.CharField(max_length=50)),
                ("capacite", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ram", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_archivage", models.DateTimeField(auto_now_add=True)),
                ("raison", models.TextField()),
                (
                    "archive_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_produits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Boutique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("adresse", models.TextField()),
                ("ville", models.CharField(max_length=50)),
                ("code_postal", models.CharField(max_length=10)),
                ("departement", models.CharField(blank=True, max_length=50)),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=9, max_digits=12),
                ),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=9, max_digits=12),
                ),
                (
                    "num_telephone",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_maj", models.DateTimeField(auto_now=True)),
                (
                    "gestionnaires",
                    models.ManyToManyField(
                        blank=True,
                        related_name="boutiques_gestionnaire",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boutiques_responsable",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Modele",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "marque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boutique.marque",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("couleur", models.CharField(max_length=50)),
                ("capacite", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ram", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="produits/"),
                ),
                (
                    "modele",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produits",
                        to="boutique.modele",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("seuil_alerte", models.PositiveIntegerField(default=5)),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="boutique.boutique",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="boutique.produit",
                    ),
                ),
            ],
            options={
                "db_table": "tb_stock",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("boutique", "produit"), name="stock_composite_key"
                    )
                ],
            },
        ),
    ]
