# Generated by Django 5.2 on 2025-06-10 11:58

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Boutique",
            fields=[
                ("boutique_id", models.AutoField(primary_key=True, serialize=False)),
                ("nom_boutique", models.CharField(max_length=100)),
                ("adresse", models.TextField()),
                ("ville", models.CharField(max_length=50)),
                ("code_postal", models.CharField(max_length=10)),
                ("departement", models.CharField(blank=True, max_length=50)),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=9, max_digits=12),
                ),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=9, max_digits=12),
                ),
                (
                    "num_telephone",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_maj", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tb_boutique",
            },
        ),
        migrations.CreateModel(
            name="DemandeSuppressionProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_demande", models.DateTimeField(auto_now_add=True)),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente de validation"),
                            ("VALIDE", "Validé"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                ("raison", models.TextField(blank=True)),
                ("commentaire_responsable", models.TextField(blank=True)),
            ],
            options={
                "db_table": "tb_demande_suppression_produit",
                "ordering": ["-date_demande"],
            },
        ),
        migrations.CreateModel(
            name="HistoriqueVentes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_id", models.IntegerField()),
                ("nom_produit", models.CharField(max_length=100)),
                ("marque", models.CharField(max_length=50)),
                ("modele", models.CharField(max_length=50)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("couleur", models.CharField(max_length=50)),
                ("capacite", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ram", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_vente", models.DateTimeField(auto_now_add=True)),
                (
                    "quantite_vendue",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "tb_historique_ventes",
            },
        ),
        migrations.CreateModel(
            name="Marque",
            fields=[
                ("marque_id", models.AutoField(primary_key=True, serialize=False)),
                ("marque", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "tb_marque",
            },
        ),
        migrations.CreateModel(
            name="Modele",
            fields=[
                ("modele_id", models.AutoField(primary_key=True, serialize=False)),
                ("modele", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "tb_modele",
            },
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                ("produit_id", models.AutoField(primary_key=True, serialize=False)),
                ("nom_produit", models.CharField(max_length=100)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("couleur", models.CharField(max_length=50)),
                ("capacite", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ram", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="produits/"),
                ),
                ("validation_responsable", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "tb_produit",
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("stock_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "quantite",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("seuil_alerte", models.PositiveIntegerField(default=5)),
            ],
            options={
                "db_table": "tb_stock",
            },
        ),
        migrations.CreateModel(
            name="ArchivedBoutique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_id", models.IntegerField()),
                ("nom_boutique", models.CharField(max_length=100)),
                ("adresse", models.TextField()),
                ("ville", models.CharField(max_length=50)),
                ("code_postal", models.CharField(max_length=10)),
                ("departement", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("date_archivage", models.DateTimeField(auto_now_add=True)),
                ("raison", models.TextField()),
                (
                    "archive_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_boutiques",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tb_archive_boutique",
            },
        ),
        migrations.CreateModel(
            name="ArchivedProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_id", models.IntegerField()),
                ("nom_produit", models.CharField(max_length=100)),
                ("marque", models.CharField(max_length=50)),
                ("modele", models.CharField(max_length=50)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("couleur", models.CharField(max_length=50)),
                ("capacite", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ram", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_archivage", models.DateTimeField(auto_now_add=True)),
                ("raison", models.TextField()),
                (
                    "archive_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_produits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tb_archive_produit",
            },
        ),
    ]
