# Generated by Django 5.2 on 2025-05-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivedboutique",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="archivedboutique",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
