# Generated by Django 5.2 on 2025-05-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='est_active',
            field=models.BooleanField(default=True),
        ),
    ]
