# Generated by Django 5.2 on 2025-05-22 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
        ('free_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='gestionnaires',
            field=models.ManyToManyField(blank=True, related_name='boutiques_gestionnaire', to='free_app.userprofile'),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boutiques_responsable', to='free_app.userprofile'),
        ),
    ]
