# Generated by Django 5.2 on 2025-05-14 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0002_alter_archivedboutique_latitude_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="archivedboutique",
            old_name="nom",
            new_name="nom_boutique",
        ),
        migrations.RenameField(
            model_name="archivedproduit",
            old_name="nom",
            new_name="nom_produit",
        ),
        migrations.RenameField(
            model_name="boutique",
            old_name="nom",
            new_name="nom_boutique",
        ),
        migrations.RenameField(
            model_name="marque",
            old_name="nom",
            new_name="marque",
        ),
        migrations.RenameField(
            model_name="modele",
            old_name="nom",
            new_name="modele",
        ),
        migrations.RenameField(
            model_name="produit",
            old_name="nom",
            new_name="nom_produit",
        ),
        migrations.RemoveField(
            model_name="boutique",
            name="id",
        ),
        migrations.RemoveField(
            model_name="marque",
            name="id",
        ),
        migrations.RemoveField(
            model_name="modele",
            name="id",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="id",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="id",
        ),
        migrations.AddField(
            model_name="boutique",
            name="boutique_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="marque",
            name="marque_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="modele",
            name="modele_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="produit",
            name="produit_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="stock",
            name="stock_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name="archivedboutique",
            table="tb_historique_boutique",
        ),
        migrations.AlterModelTable(
            name="archivedproduit",
            table="tb_historique_produit",
        ),
        migrations.AlterModelTable(
            name="boutique",
            table="tb_boutique",
        ),
        migrations.AlterModelTable(
            name="marque",
            table="tb_marque",
        ),
        migrations.AlterModelTable(
            name="modele",
            table="tb_modele",
        ),
        migrations.AlterModelTable(
            name="produit",
            table="tb_produit",
        ),
        migrations.CreateModel(
            name="HistoriqueVentes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_id", models.IntegerField()),
                ("nom_produit", models.CharField(max_length=100)),
                ("marque", models.CharField(max_length=50)),
                ("modele", models.CharField(max_length=50)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("couleur", models.CharField(max_length=50)),
                ("capacite", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ram", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_vente", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
                (
                    "vendu_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historique_produits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tb_historique_ventes",
            },
        ),
    ]
