# Generated by Django 5.2 on 2025-05-14 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0003_rename_nom_archivedboutique_nom_boutique_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="archivedboutique",
            table="tb_archive_boutique",
        ),
        migrations.AlterModelTable(
            name="archivedproduit",
            table="tb_archive_produit",
        ),
    ]
