# Generated by Django 5.2 on 2025-05-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0005_produit_validation_responsable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivedboutique",
            name="code_postal",
            field=models.CharField(max_length=10),
        ),
    ]
