# Generated by Django 5.2 on 2025-05-15 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0006_alter_archivedboutique_code_postal"),
    ]

    operations = [
        migrations.AddField(
            model_name="historiqueventes",
            name="quantite_vendue",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
