# Generated by Django 5.2 on 2025-05-16 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_boutique_est_active'),
        ('boutique', '0007_historiqueventes_quantite_vendue'),
    ]

    operations = [
    ]
