# Generated by Django 5.2 on 2025-06-10 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("boutique", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_id", models.IntegerField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("role", models.CharField(max_length=20)),
                ("telephone", models.CharField(blank=True, max_length=20, null=True)),
                ("date_archivage", models.DateTimeField(auto_now_add=True)),
                ("raison", models.TextField()),
                (
                    "archive_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users_archives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tb_user_archive",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("profile_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("RESPONSABLE", "Responsable de la boutique"),
                            ("GESTIONNAIRE", "Gestionnaire de laboutique"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "telephone",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_maj", models.DateTimeField(auto_now=True)),
                (
                    "boutiques",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gestionnaires_boutique",
                        to="boutique.boutique",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tb_user_profile",
            },
        ),
    ]
