# Generated by Django 5.2 on 2025-05-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("free_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="id",
        ),
        migrations.AddField(
            model_name="archiveduser",
            name="first_name",
            field=models.CharField(default="prenom", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="archiveduser",
            name="last_name",
            field=models.CharField(default="nom", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name="archiveduser",
            table="tb_user_archive",
        ),
        migrations.AlterModelTable(
            name="userprofile",
            table="tb_user_profile",
        ),
    ]
